### ISSUE TITLE
What's wrong with .map((x, i) => { return `<foo>`; }).join("") ?

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#10]
To generate e.g. the rows in a table, I often use code like
```
${rowdata.map((x, i) => `<tr>. . .</tr>`).join("")}
```
However, if I need to do something, like calculating a value v, before returning the `<tr>` code, then the following syntax should have been possible:
```
${rowdata.map((x, i) => { const v = . . .; return `<tr>. . .</tr>`; }).join("")}
```
. . . but it seems to me that AppRun doesn't like that. Is that documented somewhere?

**Comment by yysun** [comment]
Please check out this example:
https://jsfiddle.net/ap1kgyeb/6/

**Comment by yysun** [comment]
${rowdata.map((x, i) => { const v = . . .; return `<tr>${v}</tr>`; }).join("")}

**Comment by jkleiser** [comment]
I found out what bit me: I had a newline between `return` and the value to be returned. Sorry. ;-)
