### ISSUE TITLE
Broken Link in docs

### ISSUE THREAD

**Issue by JamieVaughn** [yysun/apprun#108]
There's a broken link on this docs page: https://apprun.js.org/docs/#/04-architecture#event-scope

When trying to follow link to 05-component.md it fails due to a typo in the md file: `04-component.md`

I tried pushing a branch with the fix to PR but I lack permissions.

**Comment by yysun** [comment]
Thank you. If you submit a PR, I will merge it so that you will be listed as a contributor.
