### ISSUE TITLE
First page always blank in sample.

### ISSUE THREAD

**Issue by kingsanu-production** [yysun/apprun#113]
I clone your project into my app as well in your sample for razor pages, always home("first") page showing blank. after click the home link again it going to generate data.

First time load
![image](https://user-images.githubusercontent.com/65809324/105937401-7b407d80-607b-11eb-983a-3f49159b2e26.png)

After click home link
![image](https://user-images.githubusercontent.com/65809324/105937412-81365e80-607b-11eb-98d7-1bb42966d375.png)

**Comment by yysun** [comment]
Not sure what you have done. Is it possible to share your code for me to take a look?
