### ISSUE TITLE
Can I use other libraries in place of lit-html?

### ISSUE THREAD

**Issue by tvardy** [yysun/apprun#117]
There are very cool competitors for lit-html - eg. HyperHtml, lighterhtml and uhtml by @WebReflection
Do you think I'd be able to use the with AppRun?

**Comment by yysun** [comment]
Yes you can.

**Comment by yysun** [comment]
You need to let apprun use the _render_ function from_uhtml_:
```
app.render = utml.render;
```
Here is an example:
https://apprun-uhtml.yysun.repl.co/

**Comment by tvardy** [comment]
I new there needs to be a trick with the `render`... didn't think of such an easy one :D

Thanks!

**Comment by yysun** [comment]
Here is another example:
https://apprun-uhtml-custom-element.yysun.repl.co/

**Comment by WebReflection** [comment]
not sure it's relevant but `uhtml` and `lighterhtml` have `render(where, what)` instead of `render(what, where)`:

```js
render(document.body, html`
  <h1>Hello 👋</h1>
`);
```

**Comment by yysun** [comment]
@WebReflection, AppRun also uses `render(where, what)` so it is easy to replace the AppRun render engine with uhtml.
```js
app.render = uhtml.render
```
When using lit-html, we need to switch the parameters.
```js
app.render = (e, v) => litHtml.render(v, e);
```
Currently, AppRun uses [morphdom](https://github.com/patrick-steele-idem/morphdom) for supporting HTML string in addition of JSX. I was thinking to replace morphdom with lit-html. I like uhtml more now.

**Comment by WebReflection** [comment]
uhtml uses [udomdiff](https://github.com/WebReflection/udomdiff#readme), in case it's needed 👍
