### ISSUE TITLE
global values created for ESM version

### ISSUE THREAD

**Issue by tvardy** [yysun/apprun#118]
https://github.com/yysun/apprun/blob/f16a53d8379c707b78341920d13140e490e66782/src/apprun.ts#L61-L66

becomes

https://github.com/yysun/apprun/blob/f16a53d8379c707b78341920d13140e490e66782/esm/apprun.js#L40-L45

I noticed that part accidentally while checking other things... I got surprised that even though I haven't imported the `Component` in a separate component file, the script was able to find a reference and interpret `... extends Component {` without throwing an error.

I guest the ESM version shouldn't expose global variables... this should only show up in the `dist`

**Comment by yysun** [comment]
I agree.
