### ISSUE TITLE
chrome extension devtool support?

### ISSUE THREAD

**Issue by davidm-public** [yysun/apprun#12]
Hi, just wondering if this project has a browser extension, (like elm, react, or vue have)?

**Comment by yysun** [comment]
It does not have a dev-tool currently. But this library is very suitable to have a dev-tool for monitoring events and state changes happened inside the applications. 

I am hoping someone can help create one :)

**Comment by davidmoshal** [comment]
Indeed it is. 
I'm only familiar with the Vue devtools plugin, sounds like something you might want to look at.
Challenge for you: the excellent grid component: AgGrid is written in Typescript.
I wonder what it would take to integrate with it (they have integrated it with Vue, React, etc.)
- the code is open source on github.

**Comment by yysun** [comment]
With AppRun v1.10.0, you can subscribe to the _debug_ event to log the state change before and after 
the update. As well as the change from the state to vdom by the view function:
```javascript
app.on('debug', p => console.log(p));
```

**Comment by yysun** [comment]
![image](https://user-images.githubusercontent.com/170547/38205343-40908998-3674-11e8-9027-9e7a4340efb0.png)

**Comment by yysun** [comment]
DevTools is included in v1.14.
