### ISSUE TITLE
lit-html code not working in the docs

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#128]
The code example at https://apprun.js.org/docs/getting-started/#use-lit-html seems not to work. When I click the "Try the Code" button", I get a pop-up with an empty field on the right hand side. I've tried it in both Safari and Brave.

**Comment by yysun** [comment]
Lit has release V2, I haven’t had time to update it in AppRun yet.

**Comment by yysun** [comment]
Fixed in 3.28.8
