### ISSUE TITLE
can we insert any html frame using apprun

### ISSUE THREAD

**Issue by xihajun** [yysun/apprun#138]
Hi there,

I love the apprun which allows to add the interactive objects in the documents. But may I kindly ask if it is possible to insert a html page?

Many thanks

**Comment by xihajun** [comment]
`<iframe width=700, height=500 frameBorder=0 src="xxx"></iframe>`

**Comment by yysun** [comment]
Yes you can.

**Comment by xihajun** [comment]
> Yes you can.

@yysun Thanks for your reply! May I ask if it is possible to use it with css, javascript, html files together? If so, do you have any guidance somewhere?

**Comment by yysun** [comment]
https://apprun.js.org/#play

https://apprun.js.org/docs
