### ISSUE TITLE
Does appRun support shared state?

### ISSUE THREAD

**Issue by joshua1** [yysun/apprun#14]
Does appRun support the concept of an app-wide shared state (with associated actions and vies/getters) , like you have with the likes of vuex, mobx-state-tree. or would it work with a state management library like mobx or mobx-state-tree

**Comment by joshua1** [comment]
i read this soon after asking this question
```
https://medium.com/@yiyisun/deep-dive-into-apprun-state-3d6fb58b1521
```
but then , there will be instances where it makes sense to share state between/amongst components. hwo do you achieve that

**Comment by yysun** [comment]
After you change the global state, you publish a global event to let other components take action on it.

**Comment by joshua1** [comment]
How and where is this global state defined if i may ask. seeing that each component has state, view and update objects

**Comment by yysun** [comment]
You can define a global state in a module and use an event to update and push the new global state to other components:

```javascript
import app;
const global_state = {
  counter: 0
};
app.on('update-global-state', (delta) => {
  global_state = { counter: global_state.counter + delta }
  app.run('global-state-changed', global_state)
})
```
In other components:
```javascript
import app, { Component } from 'apprun';
export default class MyComponent extends Component {
  state = {}
  view = (state) => {
    return <div>
      {state.global_state.count}
      <button onclick={app.run('update-global-state', 1)}>+1</button>
      <button onclick={app.run('update-global-state', -1)}>-1</button>
    </div>
  }
  update = {
    'global-state-changed': (state, global_state) => ({ ...state, global_state })
  }
}
```

**Comment by joshua1** [comment]
Me here again. I am looking at a scenario where the global shared state is reactive/observable like what you have in vuex. having to implement change event listeners and publishers everywhere manually might lead to loose ends . Is this possible ?

**Comment by joshua1** [comment]
@yysun thanks so much for the explanation.

**Comment by joshua1** [comment]
@yysun  Me here again on global state, seeing the  implementation of apprun-reeactive using @nx-js/observer-util, it seems  one can possibly get reactivity in a global state using observable properties and observers for (computed events). Can i use @nx-js/observer-util on a global state object /class as discussed above , or can the apprun-reactive decorator be used outside of a component

**Comment by yysun** [comment]
Here are two examples of reactivity. 
https://apprun.js.org/#play/17
https://apprun.js.org/#play/18
