### ISSUE TITLE
`for` attribute on `label`s doesn't work

### ISSUE THREAD

**Issue by mrdziuban** [yysun/apprun#143]
It seems like the `for` attribute on `label` elements has no effect when using JSX. I first noticed this in my own project and then found that it's reproducible in the apprun docs too -- https://apprun.js.org/docs/directive/#form-validation -- the `<label>` in the code snippet has a `for` attribute but the rendered HTML doesn't.

<img width="850" alt="Screenshot 2023-05-10 at 7 58 01 PM" src="https://github.com/yysun/apprun/assets/4718399/29a4a005-bd44-4d0c-9869-a837e41174dd">

Any thoughts you have would be appreciated. Thank you for all your work on this library!

**Comment by yysun** [comment]
Thank you for reporting the issue. It has been fixed in v3.31.0 now.
