### ISSUE TITLE
using reactive properties with the web component 

### ISSUE THREAD

**Issue by sanabel-al-firdaws** [yysun/apprun#147]
Is there a way to archive this ? cuz i would love to make components in this library and use it in other projects

```html
<my-element myvalue="99"></my-element>
```

**Comment by sanabel-al-firdaws** [comment]
this is the closest example i can find https://apprun.js.org/#play/11

an example of the above in apprun would be so usefull for many

**Comment by yysun** [comment]
https://github.com/yysun/apprun/blob/master/demo/components/web-components.tsx
