### ISSUE TITLE
How can I use external packages with apprun

### ISSUE THREAD

**Issue by mmarkelov** [yysun/apprun#15]
Good day! Thank you for your tool!
How can I use apprun with external libraries such as [pikaday](https://www.npmjs.com/package/pikaday) in my SPA. Thanks a lot!

**Comment by yysun** [comment]
You can use the _rendered_ function to enable pikaday. 
View source of this demo: https://jewel-poison.glitch.me

**Comment by mapkeji** [comment]
Thanks a lot!

**Comment by mmarkelov** [comment]
I tried to add pikaday in my Home component, but something is wrong with it can you please check my repo [example](https://github.com/mmarkelov/apprun-test)?

**Comment by yysun** [comment]
You can set the _rendered_ function to the Home component. Check out the PR for your example project.
```javascript
const home = new Home();
home.rendered = () => {
  if (!pikaday)
    pikaday = new Pikaday({ field: document.getElementById('datepicker') });
}
home.mount(element);
```

**Comment by mmarkelov** [comment]
@yysun yeah! Thank you very much!

**Comment by yysun** [comment]
Fixed a bug in app.d.ts. Upgrade to 1.10.2, you can set rendered inside the home component.
```javascript
export default class HomeComponent extends Component {
  state = 'Home';
  view = state => { ... };
  update = { ... };
  rendered = () => {
    new Pikaday({ field: document.getElementById('datepicker') });
  };
}
```

**Comment by yysun** [comment]
The _today_ event is a local event of the component, use **this.run** to tigger it.
<button onclick={() => **this.run**('today')}>Change Datepicker</button>

BTW, the _rendered_ function has the state as the parameter, so you can do:

```
rendered = state => {
    state.pickaday = new Pikaday({ field: document.getElementById('datepicker') });
};
```

**Comment by mmarkelov** [comment]
@yysun Thank you! Once again - works like a charm!
