### ISSUE TITLE
"onclick" is not rendered in button element

### ISSUE THREAD

**Issue by nicoandresr** [yysun/apprun#16]
Hi, I'm try this great library, but i am frutrated by a mistake, I'm follow the apprun + parcel example but i don have the render expected for the button element, I expect:
```js
<button onclick="app.run('+1')">+1</button>
```
But, I only got:
```js
<button>+1</button>
```

I don't understand why!, =(

PD: I don't got any error in console.

Please check it out my [project](https://github.com/nicoandresr/nicoandresr.github.io/tree/master/apprun) =)

**Comment by yysun** [comment]
Since you are using JSX, try this:
```javascript
<button onclick={()=>app.run('+1')}>+1</button>
```

**Comment by nicoandresr** [comment]
Perfect! works, sorry for my lack knowledge! 😸

**Comment by nicoandresr** [comment]
Perfect! works, sorry for my lack knowledge! 😸
