### ISSUE TITLE
AppRun + other compile-To-JS languages?

### ISSUE THREAD

**Issue by tskalczynski** [yysun/apprun#20]
Hello,

   Would it be possible to use AppRun with some functional languages compiled to JS? I am looking for some small footprint solution (would love to use ClojureScript, but its big loading to the browser).

   Have been thinking about one of the following:

   AppRun + https://github.com/BuckleScript/bucklescript
   AppRun + https://github.com/fable-compiler/Fable
   AppRun + https://github.com/anko/eslisp
   AppRun + https://github.com/jbr/sibilant
   AppRun + https://github.com/purescript/purescript

   Can you give me some info, hint on that?   

Thank you! :)
Best regards,

Tom

**Comment by yysun** [comment]
It is totally possible as long as the language can 1) import AppRun module and 2) can create JavaScript objects.

1.  import app from 'apprun';
2. define an initial state object
3. create the view function that converts state into HTML string or virtual DOM
4. define the update object that has event handlers
5. call app.start to tie the state, view and update to an element Id

**Comment by tskalczynski** [comment]
Hello,

   Thank you! :)

   Gonna try it with BuckleScript and PureScript :).

Cheers! :)

Tom

**Comment by artyprog** [comment]
Hey Tom,

Great idea from BuckleScript. Don't forget to give your feedbacks :-)

Regards
