### ISSUE TITLE
'this' is undefined inside @update decorated function

### ISSUE THREAD

**Issue by ludmiloff** [yysun/apprun#23]
Example code to reproduce:

```
export default class TestComponent extends Component {
  state = '1';

  view = (state) => {
    return <div>
      <h1>Test</h1>
      <button onclick={_ => this.run('test')} >Test</button>
    </div>
  }

  @update("test", {render: true})
  onTest(state) {
    console.assert(this !== undefined, "'this' is undefined")
    return state;
  }

  // @on("test1")
  // test = (state) => {
  //   console.assert(this !== undefined, "'this' is undefined")
  //   return state;
  // }

  update = {
    '#TTT': state => state,
  }
}
```

But when  `@on('test') test = (state) => {....}` is uncommented,  (_note @on is on another message_) then assertion is ok;
If only @on decorator is used then everything works well too. 
Hope I've explained it.

**Comment by yysun** [comment]
I have pushed the fix. The following test is a pass now.

``` javascript
  it('should support this in @update', done => {
    class TestComponent extends Component {
      view = state => state
      @update('test')
      onTest(state, val) {
        expect(this).not.toBeUndefined();
        done();
      }
    }
    const test = new TestComponent().mount();
    test.run('test');
  })
```

**Comment by ludmiloff** [comment]
That should work. May I suggest to bind(this) only if @update decorator is used, because @on decorator obviously catch **this** naturally using **=>** operator
To achieve this you have to attach two distinct metadata keys - say apprun-update and apprun-on respectively.

Thanks for your quick fix

**Comment by yysun** [comment]
Thank you @ludmiloff. I used _bind_ for both cases just in case one is not using =>
```javascript
 @on("test")
 test = function (state) { return state; }
```

**Comment by ludmiloff** [comment]
You are absolutely correct. Thanks again.
