### ISSUE TITLE
Allow ROUTER_EVENT handler (//) to stop propagation of other event (#SomeComponent)

### ISSUE THREAD

**Issue by ludmiloff** [yysun/apprun#25]
There are certain cases when firing #SomeComponent event from router should be stoped if no conditions met. 
Example:
User click on link witch leads to restricted area (user profile etc) and login form must be popped first, then on successful login the page should be displayed.

If I'm able to catch such route in (//) handler and stop #Profile event, I could easily fire #Login event with proper parameter #Profile as returnURL.

With current router implementation I'm firing the another event (#Login), but #Profile event is fired too.

**Comment by yysun** [comment]
I think you can do it without using the // event.
```JavaScript
update = {
  '#Profile': state => {
    if (!authorized) {
      app.run('#Login', {returnURL: '#Profile'});
        return; // this stops the event
     }
     //....
     return state;
  }
}
```

**Comment by ludmiloff** [comment]
Thanks for solution. 
Anyway, I'm still confused about:
1. What is the purpose of ROUTER_EVENT handler, if not general handling use cases like mine?
2. The code above should be placed in every component that needs authorization or similar conditions to run and leads to code duplication. I know I can create a function which do the same thing to minimize duplication.

My proposal:
`
export interface IApp 
{
  ....
  // Router Event Handler; initially does nothing
  onRoute(name: string, ...rest): boolean
}

...
// Router Event Handler; initially does nothing
app.onRoute(name: string, ...rest) {}
`

then in route function:
`
if (app.onRoute(name, ...rest) app.run(name, ...rest);
`

and finally in client code:
`
// set new onRoute handler
`

app.onRoute = (name :string, ...rest) => {
  if (!authorized) { 
    app.run("#Login, {returnURL: name});
    return false; // block #name event
  }
  ....
  return true; // allow #name event
}

What you think about?

**Comment by yysun** [comment]
Not too much use of the ROUTER_EVENT event currently. I only use it to set active menu.

I usually check user permission in each component. It just needs one line.
```JavaScript
update = {
  '#Profile': state => {
    if (!authorized) return app.run('#Login', {returnURL: '#Profile'}); // this stops the event
    //....
    return state;
  }
}
```
If you wan to have a centralized authorization, you can add another internal event.
```JavaScript
app.on('//', (name) => {
  if (!authorized(name)) app.run('#Login', {returnURL: name});
  else app.run(name + '//' ); 
})
```
Profile component shows up upon the #Profile// event, instead of #Profile.

**Comment by ludmiloff** [comment]
I really liked last one-liner approach. It doesn't work well, however.
my code:
```
import app, {Component} from 'apprun';

export default class ProfileComponent extends Component {
  state = 'Profile';

  view = (state) => {
    return <div>
      <h1>{state}</h1>
    </div>
  }

  update = {
    '#Profile//': state => state,
  }
}
```
then
```
app.on('//', route => {
  let user = app['user'];
  if (!user) {
    user = auth.getUser();
  }
  if (!user) {
      console.log("MUST LOGIN")
      app.run("#Login", {returnUrl: route})
  } else {
    app.run(route + "//")
  }
})
```

when enter url http://localhost:3000/#Profile in browser, I'm getting
**Assertion failed: No subscriber for event: #Profile** error

**Comment by yysun** [comment]
Add an empty handler to avoid the error:
app.on(‘#Profile’, ()=>{})

**Comment by ludmiloff** [comment]
Your first approach 
```
update = {
  '#Profile': state => {
    if (!authorized) return app.run('#Login', {returnURL: '#Profile'}); // this stops the event
    //....
    return state;
  }
}
```
is far better and I'll adopt it for now.
I would appreciate some centralized solution, though.

**Comment by ludmiloff** [comment]
I've just completed my idea in separate branch [https://github.com/ludmiloff/apprun/tree/patches](url) and write some tests. Will test it on a real app I'm currently working on and report later

**Comment by ludmiloff** [comment]
Hello @yysun ,
In regard to your commit **[convert / to #](https://github.com/yysun/apprun/commit/a235f1b9169426fdf8b4e5c123478292a1bc6581)**, could you explain a bit what is the point of having "#" event at all.
The [real-app-example](https://github.com/gothinkster/apprun-realworld-example-app) example and route function from apprun show only a useless (IMO) url splitting and rewriting again. So, I wonder what is the real purpose?

**Comment by yysun** [comment]
Some applications use the convention of #, #Home, #About and #Contact, in like the default Bootstrap template. AppRun by default supports this convention. The real-world example uses a different convention of #/, #/Profile and etc.. Therefore in the real-world example, we use // to handle it.

In order to support SSR, the commit 536e186 breaks the default convention that it fires / instead of #. Other applications started to fail. Therefore, it has to converts / to # to make other applications work.

**Comment by yysun** [comment]
BTW In the [SSR example](https://github.com/yysun/apprun-ssr), it is expecting / for the home page. The # is converted to / in the main.tsx.
```JavaScript
app.on('#', () => app.run('/'));
```
I am going to add this line to AppRun router, so that it fires both / and # when the application starts.

**Comment by yysun** [comment]
OK
