### ISSUE TITLE
Web Component

### ISSUE THREAD

**Issue by artyprog** [yysun/apprun#28]
Hello,

Thanks for AppRun

Could publish on StackBlitz a working sample of a counter compoment (not the list one)?
Thanks
Regards

**Comment by yysun** [comment]
https://apprun-web-component.stackblitz.io

**Comment by nicoandresr** [comment]
its broken 😿 
![captura de pantalla 2018-07-11 a la s 9 50 56 a m](https://user-images.githubusercontent.com/6032385/42580381-ffb8afca-84ef-11e8-9384-231cbb985378.png)

**Comment by yysun** [comment]
Which browser are you using? It might not support the web components.

You can try it in Chrome.
![image](https://user-images.githubusercontent.com/170547/42580787-54d0d466-84f9-11e8-8bdd-cf8754cd7845.png)

**Comment by yysun** [comment]
https://caniuse.com/#feat=custom-elementsv1

![image](https://user-images.githubusercontent.com/170547/42581365-94f13012-84fa-11e8-822f-521b3dfa9826.png)

**Comment by nicoandresr** [comment]
Yes I'm using firefox :'(

**Comment by artyprog** [comment]
Thank you yysun
In order to make it works on firefox 
could you add <script src="https://cdnjs.cloudflare.com/ajax/libs/custom-elements/1.1.2/custom-elements.min.js"></script>

Regards

**Comment by artyprog** [comment]
I made the counter visible in Firefox 
[https://apprun-web-component.stackblitz.io/ ](https://apprun-web-component.stackblitz.io/)

But I get the error  **counter.run is not a function**

**Comment by yysun** [comment]
Try this:
https://apprun-web-component-firefox.stackblitz.io

**Comment by artyprog** [comment]
Great, thank you very much.
You can close this issue if you want
Regards

**Comment by nicoandresr** [comment]
Thank U, @yysun.

**Comment by yysun** [comment]
Closing this issue with a comment: an space made it work. Looks like a bug from the polyfill.
```html
<my-app id='counter'></my-app>  <!-- not working -->
<my-app id='counter'> </my-app> <!-- works -->
```
