### ISSUE TITLE
Using "app.run()" outside view and state

### ISSUE THREAD

**Issue by Kogumelo** [yysun/apprun#38]
Hi, @yysun ! First let me congratulate you for this great job. 

I've been experimenting to build my own components using lots of different frameworks outthere to see which one suits best for me. Now that I found AppRun, with this ELM approach (a very good choice of yours!), I think I found what I want.

My first component is a simple countdown timer, nothing fancy, but usefull and good for my trials. I'm passing to it 2 parameters: 
  - init = a number (in seconds) to begin the countdown 
  - blink = another number so the counter starts blinking (to advice it's almost ending). 

I`m having some trouble, most likely due my inexperience, on calling app.run( "reset" ) - in fact, this.run( "reset" ) - on Constructor method. My code is like this:
````
export default class LwbTimerComponent extends Component {

  constructor( { init, blink } ) {
     super();
     this.initCounter = init;
     this.initBlink = blink;
     this.run( "reset" );   //  *** app.ts:30 Assertion failed: No subscriber for event: reset ***
     this.ptTimer = setInterval( () => this.run( "decrease" ), 1000 );
  }
  model = {
     secondsToGo: this.initCounter,
     ...
  }
  view = { ... }
  update = {
    "#LwbTimer": model => model,
    "decrease" : model => { ... },
    "reset": model => { 
         model.secondsToGo = this.initCounter;
         ... 
    },
   "blink": model => { ... },
 }
}
````
The compiler is telling me that "Assertion failed: No subscriber for event: reset" on run.app( "reset" ).
Clearly I defined "reset" event on update method, but something is missing.
What am I doing wrong?

**Comment by yysun** [comment]
Thank you for your interests and comments in AppRun.

We don't publish events in the constructor, because the events have not registered at that moment.
You might not need the "reset" event. Can you please try to use this line:
```
this.model.secondsToGo = init
```
to replace
```
this.run( "reset" );
```
in the constructor.

**Comment by Kogumelo** [comment]
Probably it will work, but what about
```
this.ptTimer = setInterval( () => this.run( "decrease" ), 1000 );
```
or something equivalent? When should I initialize the timer? Or, in other words, is there a "moment", a "life-cycle" timing that i could use the "app.run" command without problems and that occurs maybe right after all events were registered, but not at "update" nor "view" methods?

**Comment by yysun** [comment]
Yes, you can initialize the timer in the constructor, but be careful is the _this_ keyword in the timer callback might be _window_, not the component. 

To answer your question about the life-cycle timing, there are two ways to create the component.

Method 1: using code
```
const component = new MyComponent();
component.mount('my-element');
componenent.run('reset', 0);
```

Method 2: using JSX to compose the components (like React)
```
<MyComponent init="0" />
```
There is a life-cycle method called _mounted_ that AppRun will call right after AppRun created and mounted the component. 
```
class MyComponent extends Component {
    state = {}
    view = ...
    update = {}
    mounted = (props} => {
        this.run('reset', props.init);
    }
}
```

**Comment by Kogumelo** [comment]
Ahh! Much better, 'mounted' method now worked just fine both for "app.run('reset')" and "setInterval".

One more thing, please. At "decrease" event on "update" method, i have this comparison:
```
model.secondsToGo -= 1;
if( model.secondsToGo === this.initBlink )  this.run( "blink" );
```
Inspecting, both "secondsToGo" and "initBlink" are typed as "number", but "===" (triple equals) does not work, only when I use "==" (double equals).
Is there a reason or am I doing something wrong?

**Comment by yysun** [comment]
In the event handler, the model parameter has no type defined.
```
"decrease" : model => { ... },
```
If you have a type definition for the model. e.g.,
```
type Model = {
    secondsToGo: number;
}
```
You can add the type to the parameter.
```
"decrease" : (model: Model) => { ... },
```

**Comment by Kogumelo** [comment]
No, or it didn't work, or I did something wrong (again, sorry). I created the type Model as:
``` 
type Model = {
  secondsToGo: number,
}
export default class LwbTimerComponent extends Component {
   model: Model = { secondsToGo: this.initCounter,  }
...
   "decrease" : ( model: Model ) => { 
        if( model.secondsToGo === this.initBlink. )
        ...
```
And it is still just working with double equals, not tripple. Both are typed "number"

**Comment by yysun** [comment]
I don’t see, but how did you define the type for this.initBlink?

**Comment by yysun** [comment]
Yes, if you don’t mind.

**Comment by Kogumelo** [comment]
```
import app, {Component} from 'apprun';

type Model = {
  secondsToGo: number,
  isExpired: boolean;
  isBlinking: boolean;
}

export default class LwbTimerComponent extends Component {
  
  private initCounter: number = 0;
  private initBlink: number = 0;
  private withIcon: boolean = false;
  private ptTimer: number;

  // init = value of timer in seconds to begin countdown
  // blink = value of timer in second when it starts blinking
  // icon = true/false if it the icon is to be shown
  constructor( { init, blink, icon } ) {
    super();
    this.initCounter = init;
    this.initBlink = blink;
    this.withIcon = icon;
  }

  // model = states that need to be observed
  model: Model = {
    secondsToGo: this.initCounter,
    isExpired: false,
    isBlinking: false,
  }
    
  // Life-cycle hook for when the Component is created, mounted and ready to use
  // receive the same ( props ) passed to the Constructor
  mounted = ( props ) => {
    console.log('mounted');
    this.run( 'reset' );
    this.ptTimer = setInterval( () => this.run( "decrease" ), 1000 );
  }

  // view = how this componet is seen on browser and how the events are presented
  view = model => {
    const hh = Math.floor( model.secondsToGo / 3600 );
    const mm = Math.floor( ( model.secondsToGo % 3600 ) / 60 );
    const ss = model.secondsToGo - hh*3600 - mm*60;
    console.log(`${hh} ${mm} ${ss}`);

    return 
      <div onclick={ e => this.run( "reset" ) } class={ "lwb-timer " + ( model.isBlinking ? "isBlinking" : ( model.isExpired ? "isExpired" : "timer" ) ) }>
        { this.withIcon ? <img src='LwbTimer.svg' class='lwb-icon' /> : "" }
        <span>{ ( hh > 0 ? hh + ":" : "" ) }</span>
        <span>{ ( mm < 10 ? "0" : "" ) + mm + ":" }</span>
        <span>{ ( ss < 10 ? "0" : "" ) + ss }</span>
      </div>
  }

  // update = how the model is updated, responding to events (app.run / this.run)
  update = {
    "#LwbTimer": model => model,

    "reset": model => { 
      console.log('reset');
      if( !model.isExpired ) {
        model.secondsToGo = this.initCounter;
        model.isExpired = false; 
        model.isBlinking = false;
        return model;
      }
    },

    "expired": model => {
      console.log( 'expired' );
      model.isExpired = true;
      model.isBlinking = false
      clearInterval( this.ptTimer ); 
      return model;
    },

    "blinking": model => {
      console.log( 'blinking' );
      model.isBlinking = true;
      return model;
    },

    "decrease": ( model: Model ) => {
      model.secondsToGo -= 1;
      if( model.secondsToGo == this.initBlink ) {
        app.run( "blinking" );
        return;
      } 
      if( model.secondsToGo === 0 ) {
        app.run( "expired" );
        return;
      }
      return model;
    }
  }
}

```

**Comment by Kogumelo** [comment]
My "view" method is still under construction, don't worry too much on it.

**Comment by yysun** [comment]
Your code compiles w/o error with ===. Do you mean it does not run as expected?

**Comment by Kogumelo** [comment]
Yes, with == It runs ok, with === the comparison is always false

**Comment by yysun** [comment]
I don't know your logic, but you can debug your code in the browser devtool to see if it meets your expectation.

![image](https://user-images.githubusercontent.com/170547/46449045-e867d080-c757-11e8-86ad-98dd25378c4f.png)

**Comment by Kogumelo** [comment]
Another thing is the "app.run()" and "this.run()" behavior. The primer, as long as I understood, broadcasts the event to "outside" the component, while the former is only for "inside". I tried the app.run('blinking'), to broadcast it, and now I have 2 events.
On "main.tsx":
```
const update = {
  'blinking': model => { console.log( 'timer is blinking' ); return( model ) },
```
and on "LwbTimer.tsx":
```
const update = {
   'blinking': model => { console.log( 'blinking' ); return( model ) },
```
at console, these sequence of messages is like:
```
...
13    // countdown
12
11
timer is blinking  // --> that's the console.log from "main.tsx" (note that "blinking" message from the component, itself, doesn't show)
mounted  // --> that is something odd, as the component was mounted again
reset         // --> the component is reseted
20             // --> and started the countdown again
19
...
```

**Comment by yysun** [comment]
app.run publishes the global events.
this.run publishes the events inside component.

**Comment by Kogumelo** [comment]
Wow, now I got it, both of my final questions!!! 

1) With debugging, console showed me this:
```
private initBlink: number = 0;   // .Explicity typed for number, but...
...
constructor( { init, blink, icon } ) {
    ...
    // Even so, at this time, initBlink turns to be a string
    this.initBlink = blink; 

    // Because firstly I called it like this ...
    // <LwbTimer blink="20"> 
    // ... and the right way should be
    // <LwbTimer blink={20} >  ---> like this, it works!
    ...
}
...

2) app.run() and this.run() - I now understood what happend, those methods are quite excludents, app.run() publish ONLY for outside, and this.run() publish ONLY for inside. If I need to broadcast for both outside and inside, I need to publish both events.

THANK YOU SO MUCH!
