### ISSUE TITLE
Is possible render 'Fragments' like in react?

### ISSUE THREAD

**Issue by nicoandresr** [yysun/apprun#39]
In react is possible render fragments:

> A common pattern in React is for a component to return multiple elements. Fragments let you group a list of children without adding extra nodes to the DOM.

 in apprun I do can the same?

Thank u.

**Comment by yysun** [comment]
Yes, AppRun supports JSX fragments:
```
<>
  <div />
  <div />
</>
```

**Comment by nicoandresr** [comment]
Great thank u.
