### ISSUE TITLE
Run code after render (e.g. set focus)

### ISSUE THREAD

**Issue by payne8** [yysun/apprun#42]
Hey thank you so much for this awesome framework. I have used it for many small projects and am in the middle of a larger one now. One thing I am unsure how to do is setting focus on an input once the page has been rendered. I think I can just set a timeout in the constructor but I would prefer a cleaner more 'apprun'  way of doing it.

Is there currently a way to do that?

**Comment by yysun** [comment]
You can use the life cycle function, called _rendered_ to run code after rendering.
``` JavaScript
class C extends component {
  state = {}
  view = state => {}
  update = { }
  
  rendered = state => {  /* ... */ }
}
```

**Comment by payne8** [comment]
Awesome! I will go ahead and use that. Thank you so much!
