### ISSUE TITLE
AppRun + office-ui-fabric-react, is it possible?

### ISSUE THREAD

**Issue by tsteele-ndsc** [yysun/apprun#44]
I'm new to AppRun and React. I really like what I see in AppRun given my reading/research of Elm!

Likely a naive question, but I was wondering if an AppRun app could use React components?

Apologies if this is the wrong place to ask questions like this.

Thanks,
Tom

**Comment by tsteele-ndsc** [comment]
Maybe I answered my own question... Just use Fabric-JS dummy : - O

https://developer.microsoft.com/en-us/fabric-js

**Comment by yysun** [comment]
I am glad you found the answer. Regarding to Office fabric UI, my friend has an AppRun project that you might have interesting in taking a look:
https://github.com/raalahmmad/AppRun-office-ui-fabric

**Comment by tsteele-ndsc** [comment]
Not sure I'm doing this the proper way, but made the --init --spa use Fabric-JS Pivot ! ! !

![image](https://user-images.githubusercontent.com/17989693/51338481-89507200-1a4f-11e9-9985-1e5b9908550a.png)

**Comment by yysun** [comment]
Cool! Like it.
