### ISSUE TITLE
apprun-dev-tools.tsx:183 Uncaught TypeError: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by srlopez** [yysun/apprun#45]
Congratulations for this excellent work.
I really believe that you have achieved good architecture for the frontend.

I am studying it very carefully, but I still get lost in some concepts.
Anyway, I do not know if this is an issue, but I mention that simply with `npx apprun -i && npm start`, I already have this error in the console:

`AppRun DevTools 0.2: type "_apprun `help`" to list all available commands.`
`apprun-dev-tools.tsx:183 Uncaught TypeError: Cannot read property 'connect' of undefined`
`    at Object.12 (apprun-dev-tools.tsx:183)`
`    at t (bootstrap:19)`
`    at 0 (bootstrap:83)`
`    at bootstrap:83`
`    at universalModuleDefinition:9`
`    at universalModuleDefinition:1`

but `_apprun 'components'` show this
`apprun-dev-tools.tsx:133 <div id=​"my-app">​<div>​<h1>​Hello world - AppRun !​</h1>​</div>​</div>​ [{…}]`
`<- undefined`

Thanks in advance.

**Comment by yysun** [comment]
Sorry for the error.  You can fix it by one of the two ways: 1) install the
Redux DevTools extensions or 2) remove the script reference to the devtools
from the index.html file.

**Comment by yysun** [comment]
Fixed in 1.16.2
