### ISSUE TITLE
No 404/default route handling

### ISSUE THREAD

**Issue by phBalance** [yysun/apprun#46]
Hi,
  unless I'm missing something, I don't see any "normal" way to catch an attempt to route to a URL which doesn't exist (e.g. 404 or mistake in code matching an href to component event) unless I want to separately register all my routes and check them in the '//' event or create my own router.

  I have some code which implements a default route handler by returning the number of subscribers from app.run and then invoking a default event ('///' perhaps) from within the router if there are no subscribers to the URI. Shall I generate a pull request or is there some other way I've missed?

**Comment by yysun** [comment]
Than you Peter,

Currently we only handle simple cases. Please create a pull request.

Regards,

Yiyi
