### ISSUE TITLE
updateProps incorrectly handling data-*, role, and class[Name] attributes

### ISSUE THREAD

**Issue by phBalance** [yysun/apprun#47]
Hi,
  using apprun for a small website I came across some rendering mistakes that are occurring when reusing tags (which just modifies the tag's attributes):

1) data-* isn't removed correctly. The element.dataset property should be deleted.
2) role should be removed if there is no value
3) class[Name] needs to have removeAttribute called when removing it as setting element.className="" leaves the class attribute although it does successfully remove its value.

  I'm happy to generate a pull request.

**Comment by yysun** [comment]
Yes, please.

Thank you,

Yiyi
