### ISSUE TITLE
router improvements: HTML 5 history & "pretty" links

### ISSUE THREAD

**Issue by phBalance** [yysun/apprun#51]
Hi,
   presently HTML 5 history and "pretty links" aren't implemented although most of the required code is in the router already. In particular here are the issues as I see them:

1. No obvious way to initialize the router to indicate if the link approach is going to be # (location.hash) or / (location.pathname) based. Possible changes:
  a. we could add a method to app.router to allow the user to set the link approach.
  b. we could attempt to guess based on the first character of the hash and pathname. I'm not sure if there are situations where we could have problems but is there any reason to support a mix of hash and pretty links on a page?

2. Link behaviour for pretty links needs to modify the default <a> behaviour which is to GET the href. Possible changes:
  a) This is fairly easy to do outside of apprun (onclick = e => { app.route(e.currentTarget["href"]); return false;}) so we could get away with nothing changed inside apprun.
  b) The question is if it makes sense for apprun to have some kind of api exposed to make it easier to do these kind of links (say app.routerLink), require some attribute (say data-apprun-link) that is looked for during rendering, or if it should just be kept as a non code bit of functionality? I'm more in favour of something like each link being decorated with onclick = e => app.routerLink(e) as app is a global and easily accessible in javascript.

  What are your thoughts?

Thanks,
Peter

**Comment by yysun** [comment]
The core AppRun philosophy is to convert/link DOM events to AppRun events. Our intention is not to have the routing functions altogether, because applications should convert/link the _popstate_ event to AppRun events to match the applications' routing schema, such as #, #/, #:, /#/, or without the hash. 

By default, we have implemented the routing schema of using # to make it work out-of-the-box with the HREF of the A element in the bootstrap template.  E.g.,
```html
<a href='#About'>About</a>
```
Applications should publish events for other routing. E.g.,
```html
<a href='#' onclick={()=>app.run('About')}>About</a>
```
Applications can handle pretty links:
```javascript
const menus = document.querySelectorAll('.navbar-nav li a');
  for (let i = 0; i < menus.length; ++i) {
    const menu = menus[i] as HTMLAnchorElement;
    menu.onclick = event => {
      event.preventDefault();
      history.pushState(null, '', menu.href);
      app.run('route', menu.pathname);
    }
};

window.addEventListener('popstate', () => {
  setTimeout(() => {
    app.run('route', location.pathname)
  });
});
```

The built-in _route event uses the default _app.route_ function, which publish handles # and publishes the extra // and /// events. We don't include _app.route_  in the apprun.d.ts. 

If applications implement own routing schema and overwrite _app['route']_, _app.run('route', should invoke the function defined in _app['route']_.

Does it make sense?

**Comment by yysun** [comment]
a68aaf3 allows removing and overriding the default route function.

**Comment by phBalance** [comment]
Hi @yysun,
  understanding the philosophy is the key here. It makes sense to do this in the application and I have no problem with that.

  Having the ability to overwrite the default router is a requirement and it's nice to have support for that functionality. Looking at your change (a68aaf39cfd64ee9af450045c41ad8f70d74d068) I can see at least one problem:
- The DOMContentLoaded listener can't be removed which means that an application app.route, as opposed to the default app.route, will be called with url=location.hash which might not be what is desired. It could also have the effect of overwriting the application's binding to onpopstate directly in the code. Some possible solutions:

- Provide a method to bind a new router that cleans up the default router including this listener.
- Require the application to provide this functionality.
- Make a separate, albeit small, package with the default router functionality. This would force an application to choose between writing their own router or using the basic hash one.

  Thoughts?

**Comment by yysun** [comment]
The default router function in your 3rd point is the _route_ function from _router.ts_. By default it is stored in the global _app_ instance as _app['route']_.

1. Applications can remove 
```javascript
app['route'] = null;
``` 
In this case DOMContentLoaded wont do anything if the _app['route']_ is not the default one.

2. Application can also override the default router:
```javascript
app['route'] = url => { /* handle url, fire events */};
```
* The new router function in _app['route']_ will be called by the _router_ event.
```javascript
app.run('route', url);
```
* The new router function in _app['route']_ will not be called from the _window.onpopstate_  event. Applications need to listen to the _window.onpopstate_ event to handle location.hash or location.pathname.

```javascript
app.run('route', menu.pathname);
app.run('route', location.pathname)
```
The change is 69b3623.

I think it is cleaner. What do you think?

**Comment by phBalance** [comment]
That solves the problem just fine. Thanks for the changes! The only thing that would be "cleaner" would be to have a router in a separate package but I see value having something that works out of the box. Adding a new router on top is minimal size overhead anyways.
