### ISSUE TITLE
Property className cannot be assigned to Component's wrapper div 

### ISSUE THREAD

**Issue by bo-kh** [yysun/apprun#57]
AppRun always wraps up Component in an extra div. It's not so convenient from CSS point of view, but it even less convenient that a developer cannot add any CSS style rules to the wrapping (parent) div by CSS class name, because it looks like the only property Component's parent div handles is Id. 
If there is no way to remove parent extra div could you add an ability to define className property to the parent div?

**Comment by yysun** [comment]
You can define the class or CSS in the view function of your components.
```javascript
class MyClass extends Component {

  view = state => <div class='myClass' styles={{ 'color': 'red' }}>
  </div>

}
```

**Comment by bo-kh** [comment]
I will explain my thoughts with a simplified example. Let's pretend I have a useful stateful component Stars.tsx that I would like to re-use in my application several times:

Stars.tsx
```javascript
import app, {Component} from 'apprun';

export default class Stars extends Component
{
  view = state => <div class="stars">
    <span>Here should be stars...</span>
  </div>
}

```
In my main.tsx (for example) I would like to re-use this component this way:

```javascript
import app from 'apprun';

import Stars from './Stars';

const view = state => <div className="container">
  <h2>Stars app</h2>
  <Stars id="star1" className="stars-new" />
  <Stars id="star2" className="stars-new" />
</div>;

app.start('main', {}, view, {});

```
After I have run this example I will see the next situation in devTool:
![image](https://user-images.githubusercontent.com/17910553/55351147-4175ae80-54c6-11e9-9a5d-b4353026b349.png)

Here are two wrapping divs with Ids "star1" and "star2" that Component adds (not me :))

So, the question is: could I suppress wrapping div creating in stateful components or could you add at least an ability to handle className property in this wrapping div that a developer could apply CSS rules by class name (in my example "stars-new")? It's not good to define these divs' CSS rules by id every time I use Stars component.

**Comment by yysun** [comment]
I see. AppRun components have to mount to an element, so we cannot remove
the wrapper div. But we can try to apply the class name to the div.

**Comment by yysun** [comment]
I have pushed a fix 7ca2764. It sets props to the div wrapper.
```javascript
  it("should set props to child component's div wrapper", () => {
    class Child extends Component {
    }
    class Main extends Component {
      view = _ => <>
        <Child class="c1" id="c1" />
        <Child className="c2" />
        <Child style={{ 'color': 'red' }} />
        <Child data-a='a' />
      </>;
    }
    const element = document.createElement('div');
    app.render(element, <Main />);
    const main = element.children[0];
    expect(main.children[0].id).toBe("c1");
    expect(main.children[0].className).toBe("c1");
    expect(main.children[1].className).toBe("c2");
    expect((main.children[2] as HTMLDivElement).style.color).toBe("red");
    expect((main.children[3] as HTMLDivElement).dataset.a).toBe("a");
  });
```

**Comment by bo-kh** [comment]
Thank you! The fix looks good and simple. So far I like this small but very powerful library.

**Comment by yysun** [comment]
@bo-kh, I am thinking to change the component wrapper element from _div_ to _section_. Will this change break your code?

**Comment by bo-kh** [comment]
@yysun, No, this change doesn't affect my code much. Semantically `section` suits better for the component wrapper purpose

**Comment by yysun** [comment]
Changed in 1.18.2.
