### ISSUE TITLE
New view includes element from old view

### ISSUE THREAD

**Issue by chancyk** [yysun/apprun#58]
I ran into a very simple case which seems like unusual behavior to me, but I'm not sure if it's by design or not. 

In the example below, the `<button>` is being rendered in the new view even though it should be a solitary `<div>`.  If I wrap the entire view in another `<div>`, then we get the proper behavior. If this is by design, that the view must be wrapped in a single top-level element, I wonder if there's a way to emit an error when someone experiments with a view as below?

```html
<html>

<head>
    <script src="https://unpkg.com/apprun@latest/dist/apprun-html.js"></script>
</head>

<body>

<div id="file-processor"></div>

<script>

function read_files(state){
    const el = document.getElementById('file-upload');
    state.files = el.files;
    return state;
}

const state = {
    files: []
};
const view = state => {
    var new_view = null;
    if (state.files.length == 0){
        new_view = `<input type="file"
            id="file-upload" name="files"
            accept=".csv"
            multiple>

        <button onclick='app.run("read-files")'>Load Files</button>`;
    }
    else {
        new_view = `<div>Files: ${state.files.length}</div>`;
    }
    return new_view;
};
const update = {
    'read-files': state => read_files(state),
};
app.start('file-processor', state, view, update);

</script>
</body>
</html>
```

**Comment by yysun** [comment]
Confirmed the issue. Working on a fix. The workaround is to use a single root.
