### ISSUE TITLE
Improve Example

### ISSUE THREAD

**Issue by andreaschiona** [yysun/apprun#59]
Hi,

at the moment I'm working on an [demo todo application](https://github.com/andreaschiona/apprun-springboot-todoapp)
) where the frontend is based on AppRun and the backend on Spring Boot.

My "problem" now is to understand the "right way" to call backend api (expose by rest) from the frontend. 
Can you give me a simple example, please?

Thanks,
Andrea

**Comment by yysun** [comment]
Here is an example.

https://apprun.js.org/#play/8

Regards,

Yiyi

**Comment by andreaschiona** [comment]
Thanks!

Regards,
Andrea
