### ISSUE TITLE
'var state = 0;' instead of 'const state = 0;'

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#6]
In the counter example under "Quick Start", I would have expected to see `var state = 0;` instead of `const state = 0;`.

**Comment by yysun** [comment]
Good point! Using const means that the state is immutable. The state variable is just the initial state. Once the app starts, changing the state variable directly has no effects. Only the functions in the update create and return new states. The const can prevent people from changing the state variable.

**Comment by jkleiser** [comment]
I see! Then, to make it clearer, I prefer to change the `state` identifier in this line, and in the line calling `app.start`, with `initialState` (and keep the `const`).

**Comment by yysun** [comment]
Please feel free to name the initial state. It is used just one time in app.start. Or you can skip it.
```
app.start('my-app', 0, view, update)
```
I will put a comment in the quick start example:
```
// initial state
const state = 0;
```
