### ISSUE TITLE
Websocket example?

### ISSUE THREAD

**Issue by Brent-Tucker** [yysun/apprun#60]
I'd like to open a websocket once and have various components listen for different events. How would I do something like that?

ie. Create one web socket connection, receive message data from server, update chart component with message,  update geomap component with message.

 Thanks in advance.

**Comment by yysun** [comment]
AppRun is designed for event-driven programming like web socket/web worker. 

Just created a demo project:
https://github.com/yysun/apprun-websockets

**Comment by Brent-Tucker** [comment]
This is great. Thanks.
