### ISSUE TITLE
Remove runtime dependency on Commander.

### ISSUE THREAD

**Issue by MicahZoltu** [yysun/apprun#68]
A glance at Commander suggests that it is a dev-time dependency, not a runtime dependency.  Recommend moving it to a `devDependency`.  I also skimmed through the source code for this project and didn't see any reason why it should be a runtime dependency.

**Comment by MicahZoltu** [comment]
Maybe it is part of the apprun cli, which is shipped with `apprun` NPM package?  If so, can the CLI be separated into a separate package so those of us that don't use it don't need to pull in Commander?

**Comment by yysun** [comment]
The CLI uses the commander package. One package makes it simple to maintain, but If the commander package causes trouble, we can consider changing.
