### ISSUE TITLE
Extra "," between HTML elements when using Array.map

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#7]
I create six SVG polygons using the map function like this:
```
${triangles.map(t => `<polygon id="${t.id}" . . . />`)}
```
When I inspect the generated HTML code in my browser, I see extra "," between the polygon elements. Am I doing something wrong, or is it a minor bug in AppRun?
A full example can be seen here:
http://folk.uio.no/jkleiser/test/carousel.html

**Comment by yysun** [comment]
The map function returns an array of string, not a string. String interpolation `${array}` converts the array into string with ",".
```
`${[1,2,3].map(t=>t)}`  // "1,2,3"
`${[1,2,3].map(t=>t).join('')}` // "123"
```
You can fix it bu using array join function:
```
${triangles.map(t => `<polygon id="${t.id}" . . . />`).join('')}
```
BTW, I really liked your carousel example.

**Comment by jkleiser** [comment]
Thanks. The `.join('')` did the trick. (I will update the online file tomorrow.)
I really like your AppRun. The ability to make a small toy app like my carousel with everything in one file, using no build tools at all, is something I value. I can even test it directly in my favourite editor, BBEdit, and see changes immediately. I look forward to digging deeper into AppRun.

**Comment by yysun** [comment]
Thank you. You have done a perfect AppRun app. Can I get your permission to twitter the carousel example and link it from README?

**Comment by jkleiser** [comment]
Sorry for the delay. Yes, feel free to twitter and link. However, maybe it would be smarter if you grabbed a copy and included it somewhere where you have control. I have no immediate plan to remove it from "my" folk.uio.no site; I just don't know how long I will have access to my part of it.
