### ISSUE TITLE
The componentCache is never cleared. Surprising behaviour on recreated components.

### ISSUE THREAD

**Issue by maparent** [yysun/apprun#73]
There is a global componentCache declared [in component.ts](https://github.com/yysun/apprun/blob/e4ef0c7658320f9ec314e862221c16a46a6f0c3b/src/component.ts#L7). I do not see any code to delete elements from this cache, so it would leak memory in a major way. I think some last-created, or last-accessed queue with a maximum size would be helpful.

I discovered it because of another issue: I was deleting and creating components, and found that re-created elements with the same ID as a previously deleted one would have the state of the old element. This was unexpected. I think we also need a way to declare that a component is dead.

**Comment by yysun** [comment]
The componentCache is for the dev-tool to see all components. I can make it on/off based on the app['debug'] flag.

Can you please show an example of deleting and re-creating components?

**Comment by maparent** [comment]
Disabling the cache unless debug would make sense to me, no idea about performance impact?
As for reappearing components: I have put an example in [this gist](https://gist.github.com/maparent/438371ca6d2132321886526fd661b3a5). Try creating a branch with sub-elements, deleting it, recreating the deleted element, and you'll get the sub-elements back.

**Comment by maparent** [comment]
On cache performance: You seem to imply [here](https://github.com/yysun/apprun/issues/29#issuecomment-404806438) that it is useful to avoid redrawing children when the parent is refreshed, which is a case I do care about. Another case I would care about is when a child is reparented (eg in a drag and drop operation.)

**Comment by yysun** [comment]
Pushed the fix to use app['debug'] for componentCache: ffa560a6.
