### ISSUE TITLE
className="foo" vs. class="foo" in .tsx

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#82]
In your book, page 79, I read "Notice that we use className to represent the class property in JSX instead of class." That is also what one does in React. However, when I create a new SPA by doing `npx apprun --init --spa`, the file main.tsx that I get contains a lot of className="nav*". That made think that I could use class instead of className in other .tsx files as well, and it seemed to work. Could you please explain?

**Comment by yysun** [comment]
There are new features added after the book is published. Supporting
_class_ was one of them.     I think the book is only up to 1.15/2.15.
