### ISSUE TITLE
SPA shows empty window on "Smart TV" browser

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#84]
I was just curious to see how my SPA behaved on my Samsung smart TV: It just gave me an empty window. This doesn't matter much to me, but I think it could have been nice if my SPA at least could show some message like "This app requires XYZ". To start with, I'd have to figure out which browser feature(s) to test.
I tested my "smart TV" browser using whatsmybrowser.org, and the results were available at https://whatsmybrowser.org/b/5UVF59K. Here's the results:
```
Operating system	Linux
Javascript enabled	Yes
Cookies enabled	Yes
Flash version	Not installed
Java version	Not installed
Websockets supported	Yes
WebGL supported	Yes
Language	nn-NO
Browser size	1280 x 623
Screen size	1920 x 1080
Color depth	24 bit
AdBlock enabled	No

Your full user agent string is:
Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1
```
My SPA does not use Bootstrap or jQuery. I coded the needed CSS myself, not too much.
Do the results listed above tell what this "smart TV" browser is missing?

**Comment by yysun** [comment]
The test results did not show which version of JavaScript the smart TV
supports. ES3, ES5, or ES6.

**Comment by jkleiser** [comment]
I will try to find out.

**Comment by niutech** [comment]
It is WebKit-based Samsung Browser 1.1 and it scores [370 points in HTML5Test](http://html5test.com/s/620f2d325441bab9.html), so it should support ES5.

**Comment by yysun** [comment]
Is there a way to see the console output of the Samsung Browser?

**Comment by jkleiser** [comment]
This app https://apprun-classyui-spa.surge.sh/ behaves the same way, just an empty window. I haven't found out if it's possible to see the console output. The source for this app is here: https://github.com/jkleiser/apprun-classyui-spa

**Comment by yysun** [comment]
@jkleiser, the apprun-classyui-spa uses ES6 now.

**Comment by niutech** [comment]
The same with IE11 - blank page. Could you please support ES5? Still [6.11%](https://netmarketshare.com/browser-market-share.aspx?id=browsersDesktopVersions) uses IE11.

**Comment by yysun** [comment]
Someone told me they made IE11 by adding 3-4 polyfills. They found what’s
needed from the console output. I will take a look myself to see what are
they in IE11.

**Comment by jkleiser** [comment]
Here's an app I just made with `npx apprun --init --spa --es5`:
https://spa-es5.surge.sh/
On my Samsung TV it gives me the same empty window. ;-)

**Comment by yysun** [comment]
To use AppRun for applications that support IE 11, you will need:

1. Polyfills for _Promise_ and _string.startsWith_ , e.g., using https://polyfill.io
```
 <script src="https://polyfill.io/v3/polyfill.min.js?features=String.prototype.startsWith%2CPromise"></script>
```

2. Use _window.onhashchange_ in main.tsx
```
if (!window.onpopstate) window.onhashchange = () => app.route(location.hash);
```

Here is an example project: https://github.com/yysun/apprun-ie11

Not sure if Samsung TV needs more polyfills.

**Comment by yysun** [comment]
Live Demo: https://yysun.github.io/apprun-ie11

**Comment by jkleiser** [comment]
I now added the two lines to support IE 11, as described above. It made no difference to my app at https://spa-es5.surge.sh/ . Sorry. This is not important to me at all.
Your app at https://yysun.github.io/apprun-ie11 gave the same empty window on my TV. ;-)

**Comment by niutech** [comment]
@yysun Thanks, I can confirm your demo works in IE11. As for [onpopstate](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate), it should be supported in IE10+.

@jkleiser You could try including Firebug Lite in your page by putting this inside `<head>`: `<script src="https://cdnjs.cloudflare.com/ajax/libs/firebug-lite/1.4.0/firebug-lite.js"></script>` or debugging the [Samsung Smart TV Browser](https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/web-inspector.html).

**Comment by jkleiser** [comment]
@niutech I have now inserted that Firebug Lite script line into my https://spa-es5.surge.sh/. How do I activate it to use it? Is that possible on the Smart TV?

**Comment by niutech** [comment]
You forgot to append `#startOpened=true` so it looks like: `<script src="https://cdnjs.cloudflare.com/ajax/libs/firebug-lite/1.4.0/firebug-lite.js#startOpened=true"></script>`.

**Comment by jkleiser** [comment]
@niutech Thanks, it's now appended. However, when I try it at https://spa-es5.surge.sh/, the Firebug Lite seems to close just after it opened. What may be the reason?

**Comment by niutech** [comment]
It seems that AppRun is replacing the `<body>` with its contents. Try putting the Firebug Lite `<script>` just before `</body>`. However, the best way would be to use the [remote debugger for Samsung Browser](https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/web-inspector.html).

**Comment by jkleiser** [comment]
I now moved the Firebug Lite `<script>` just before the closing `</body>`. The result is the same.

**Comment by niutech** [comment]
Sorry, cannot help more. Try using the other way to debug Samsung Browser using my link above.
