### ISSUE TITLE
Probably missing \ in SPA webpack.config.js regex

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#86]
This issue is just about a tiny detail that may only confuse a "newbie" like me, but in my SPA (generated by `npx apprun --init --spa`) this line in webpack.config.js
```
{ test: /.tsx?$/, loader: 'ts-loader' },
```
should probably have been
```
{ test: /\.tsx?$/, loader: 'ts-loader' },
```
It seems to make no practical difference, though.

**Comment by yysun** [comment]
Thanks!

**Comment by jkleiser** [comment]
I cannot anylonger find info about how to create a SPA, `npx apprun --init --spa`, in your docs. What has happened?

**Comment by yysun** [comment]
It is still in the doc site: https://apprun.js.org/docs/#/01-start but missed out of README. I will add it back.

**Comment by jkleiser** [comment]
I just ran `npx apprun --init --spa`, and in the webpack.config.js of the project I got, I still see this line 15 with the missing `\`:
```
{ test: /.tsx?$/, loader: 'ts-loader' },
```

**Comment by jkleiser** [comment]
I'm also slightly confused by the fact that in the package.json of this new spa project I find
```
  "dependencies": {
    "apprun": "^2.22.2"
  },
```
When I check the Versions at https://www.npmjs.com/package/apprun, it looks like 2.22.2 is for es6, while 1.22.2 is for es5.

**Comment by yysun** [comment]
Just made es6 version as default yesterday. Working on update the CLI.
