### ISSUE TITLE
Still somewhat confused re. apprun 1.23.1 vs. 2.23.2

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#90]
My https://github.com/jkleiser/apprun-classyui-spa is still using apprun 1.23.1, and in its tsconfig.json it's now got `"target": "es2015", "module": "es2015"`. To check the new AppRun SPA, I did a plain `npx apprun --init --spa`. In that SPA project, which also had `"target": "es2015", "module": "es2015"`, the apprun dependency was 2.something, which I have now bumped to 2.23.2 without problems that I can see. However, if I try to "force" my apprun-classyui-spa to use apprun 2.23.2, by editing the package.json and then doing `npm install apprun`, then I end up with an app that has problems; the event handlers seem to be broken. Do you see where I go wrong?

**Comment by yysun** [comment]
You need to figure Babel. Please modify the .babelrc file as below:

```json
{
  "presets": [
    ["@babel/env",{
      "targets": {
        "browsers": "> 5%"
      }
    }],
    "@babel/react",
    "@babel/typescript"
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread",
    ["classy-ui/plugin", { "output": "dist" }]
  ]
}
```

**Comment by jkleiser** [comment]
Thanks a lot! It did the trick.
