### ISSUE TITLE
Problem with 'output' element and 2.23.9

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#93]
After upgrading two projects from 2.23.7 to 2.23.9, I see that the value of an 'output' element is no longer rendered. My 'output' element is typically coded like this:
```
<output value={state.count} />
```
I first noticed this in my github.com/jkleiser/apprun-classyui-spa, however, this repo is still at 2.23.7. I then recreated the problem in a basic AppRun SPA.

**Comment by yysun** [comment]
I found the cause. Will release a fix in 2.23.10.

**Comment by yysun** [comment]
I have release 2.23.10 and tested that can fix the the problem.

**Comment by jkleiser** [comment]
Thanks. It's working great again.
