### ISSUE TITLE
Doubling components on the screen

### ISSUE THREAD

**Issue by svkior** [yysun/apprun#95]
I've written example to reproduce the bug.

https://github.com/svkior/apprunissue1

##  How to reproduce

I have two components which receives data from backend (I simulate this with setInterval functions). When I trigger app.run by clicking on the button,  second component is rendered instead of first one.

## Expected

Do nothing.

**Comment by yysun** [comment]
If you don't want the component to render, you should return nothing. E.g., instead of
```javascript
const update = {
  "do_nothing": (state) => ({
    ...state, // DO NOTHING!!!!
  }),
}
```
do not return the state
```javascript
const update = {
  "do_nothing": (state) => {
  // update date quietly
  },
}

**Comment by svkior** [comment]
I Please forgive me, I probably didn’t explain it correctly. I reduced my current project to a minimum in order to demonstrate the problem.

The problem was that with any change in _state_ in the browser, the second component is doubled and overwrites the first component. If I use a function instead of components, then everything will be correct.

**Comment by yysun** [comment]
I see. I will look into it.

**Comment by yysun** [comment]
The workaround is to add id for the components.
```javascript
 <BottomPanel id="bottomPanel"/>
```

**Comment by svkior** [comment]
upgrade to 2.23.16 helped. Thank You
