### ISSUE TITLE
Snowpack template for AppRun?

### ISSUE THREAD

**Issue by jkleiser** [yysun/apprun#99]
I just read about Snowpack and think it looks quite interesting, but I have not had time to try it yet. If Snowpack should turn out to become an important build tool for web apps, then it could be interesting to have an official Snowpack template for AppRun. A pull request is what they ask for. Just an idea from me.
https://www.snowpack.dev/#official-app-templates

**Comment by yysun** [comment]
I like this idea.

**Comment by yysun** [comment]
https://github.com/apprunjs/apprun-snowpack

**Comment by yysun** [comment]
An alternative approach is to use esm-server. It also provides fast unbundled development experiences.
 
https://github.com/yysun/esm-server
demo: https://github.com/yysun/apprun-esm-server
doc:  https://dev.to/yysun/a-dev-server-supports-esm-3cea
